:cmock:
  :callback_after_arg_check: 0
  :mock_path: .
  :mock_prefix: mock_
  :when_ptr: :smart
  :when_no_prototypes: :warn
  :verbosity: 2
  :plugins:
    - :ignore
    - :ignore_arg
    - :array
    - :cexception
    - :callback
    - :return_thru_ptr
